import time
print("Buat folder yang dimana folder tersebut akan menjadi nama repositori kita")
time.sleep(2.5)
print("Misalkan : Belajar-Git")
time.sleep(2.5)
print("1. Masuk ke dalam folder 'Belajar-Git'.")
time.sleep(2.5)
print("2. Kemudian ketikkan perintah 'git init',")
time.sleep(2.5)
print("   maka folder 'Belajar-Git' sudah menjadi repositori.")
time.sleep(2.5)
print("3. Kemudian misal kita buat sebuah file dengan nama 'file1.txt'.")
time.sleep(2.5)
print("   Maka 'file1.txt' tersebut masih berada di Working Directory.")
time.sleep(2.5)
print("4. Untuk menambahkan 'file1.txt' ke dalam Staging Index gunakan")
time.sleep(3)
print("   perintah 'git add <nama file>', contoh kasus disini nama filenya")
time.sleep(3)
print("   'file1.txt'. Maka 'file1.txt' sudah masuk ke Staging Index dan")
time.sleep(3)
print("   siap untuk di commit.")
time.sleep(2.5)
print("5. Untuk melakukan commit kita perlu menggunakan perintah 'git commit',")
time.sleep(3)
print('   atau dengan git commit -m "Pesan Yang Ingin Disampaikan".')
time.sleep(2.5)
print('   Misalnya : git commit -m "Menambahkan file1.txt ke dalam repository".')
time.sleep(3)
print("6. Untuk mengetahui status kita dapat menggunakan perintah 'git status'")
time.sleep(2.5)
print("   Kondisi : ")
time.sleep(2.5)
print("     - Apabila berwarna merah, berarti masih berada di dalam Working Directory.")
time.sleep(3)
print("     - Apabila berwarna hijau, berarti sudah berada di dalam Staging Index.")
time.sleep(3)
print("7. Misalkan kita melakukan perubahan di dalam 'file1.txt', kita dapat mengetahui")
time.sleep(2.8)
print("   perubahan yang terjadi dengan menggunakan perintah 'git status' yang akan")
time.sleep(2.8)
print("   memberitahukan bahwa 'file1.txt' di-modified,")
time.sleep(2.5)
print("   dan juga bisa menggunakan perintah 'git diff' dimana kita secara langsung dapat")
time.sleep(3)
print("   melihat apa yang baru saja ditambahkan, atau dihapus dari 'file1.txt'")
time.sleep(2.5)
print("8. Dan ketika kita melakukan penghapusan pada sebuah file, misalnya disini 'file1.txt'")
time.sleep(3)
print("   file tersebut tidak benar-benar langsung dihapus, kita dapat me-restore filenya")
time.sleep(3)
print("   dengan menggunakan perintah 'git restore <nama file>'.")
time.sleep(2.5)
print("   Misalnya : git restore file1.txt")
time.sleep(2.5)
print("   Maka 'file1.txt' tadi akan kembali ke Working Directory")
time.sleep(2.5)
print("   Hal diatas masih bisa dilakukan apabila ketika kita men-delete 'file1.txt', kita")
time.sleep(3)
print("   belum memasukkannya ke dalam Staging Index, namun apabila terlanjur memasukkannya")
time.sleep(3)
print("   ke dalam Staging Index kita dapat menggunakan perintah sebagai berikut")
time.sleep(2.5)
print("   'git restore --staged <nama file>' dalam contoh kasus ini nama file adalah 'file1.txt'.")


